### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by raghav157** [deepinsight/mxnet-SSH#9]
INFO:root:output shape {'blockgrad0_output': (32, 800),
 'blockgrad1_output': (32, 8, 400),
 'blockgrad2_output': (32, 3200),
 'blockgrad3_output': (32, 8, 1600),
 'blockgrad4_output': (32, 12800),
 'blockgrad5_output': (32, 8, 6400),
 'rpn_bbox_loss_stride16_output': (32, 8, 1600),
 'rpn_bbox_loss_stride32_output': (32, 8, 400),
 'rpn_bbox_loss_stride8_output': (32, 8, 6400),
 'rpn_cls_prob_stride16_output': (32, 2, 3200),
 'rpn_cls_prob_stride32_output': (32, 2, 800),
 'rpn_cls_prob_stride8_output': (32, 2, 12800)}
Traceback (most recent call last):
  File "train_ssh.py", line 286, in <module>
    main()
  File "train_ssh.py", line 283, in main
    lr=args.lr, lr_step=args.lr_step)
  File "train_ssh.py", line 102, in train_net
    for k,v in arg_shape_dict.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by raghav157** [comment]
i m facing this error while running code how can i resolve it

thanks in advance

**Comment by raghav157** [comment]
got it As i am in python3 , i have to use dict.items() instead of dict.iteritems()
